twitter:
  consumer_key: "gaOLPvn1DCSUx6IkifXj4fiWq"
  consumer_secret: "sRPUDfS25ZWZXjX4yECjYAePZr5vX3bN2mCLSKhTA1cmDfOq3W"
  access_token: "301461008-KzHaSC1J5XmcQJ9HiClQ8XfuvUgG6Sg5HHkJwX0n"
  access_token_secret: "zOUrIj4MivMJuvtTxK5WSlCxV633RLLowh6RpGsulJIaj"
